movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns=[
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='updates'),
    path('delete/<int:id>/',views.delete,name='deletes'),

]

movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

# from movieproject import movieapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return  render(request,'details.html',{'movie':movie})

def add_movie(request):
    if request.method == 'POST':
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    forms=MovieForm(request.POST or None,request.FILES,instance=movie)
    if forms.is_valid():
        forms.save()
        return redirect('/')
    return render(request,'edit.html',{'form':forms,'movie':movie})

def delete(request,id):
    if request.method == 'POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return  render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Add Movie</title>-->
<!--</head>-->
<!--<body>-->
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br>
    <textarea cols="30" rows="10" name="desc" placeholder="Enter movie description"></textarea><br>
    <input type="text" name="year" placeholder="Enter movie year"><br>
    <input type="file" name="img"><br>
    <input type="submit">
</form>
{% endblock %}
<!--</body>-->
<!--</html>-->

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<nav class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand">Movies</a>
<!--  <form class="form-inline">-->
<!--&lt;!&ndash;    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">&ndash;&gt;-->
<!--&lt;!&ndash;    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>&ndash;&gt;-->
<!--  </form>-->
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  Are you sure you want to delete this movie?
  <input type="submit" value="Delete">
</form>

templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6" style="padding:15px">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6" style="padding:15px">
            <h2>{{movie.name}}</h2>
            <p>{{movie.desc}}</p>
            <h6>{{movie.year}}</h6>
             <a class="btn btn-warning" href="{% url 'movieapp:updates' movie.id %}">Update</a>
             <a class="btn btn-danger" href="{% url 'movieapp:deletes' movie.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}

templates/edit.html
<form method ="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-4" style="padding:5px">
            <div class="card" style="width: 18rem; padding:15px; max-height:600px">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}